### ISSUE TITLE
Add Yakkety Yak support to the Chromium builds

### ISSUE THREAD

**Issue by tsimonq2** [saiarcot895/chromium-ubuntu-build#1]
Although Yakkety Yak is still in Alpha, it would be good to provide packages for that, because the Chromium development builds are oriented towards the kind of crowd that would use Yakkety early on (*AHEM* like me ;) ). I'll provide code if you wish.

**Comment by saiarcot895** [comment]
Will do, considering it's now easy for me to make a package for another version of Ubuntu.

Most of the changes I'll need to make will be with my build scripts.

**Comment by tsimonq2** [comment]
Thank you, and thank you for taking the time to maintain this PPA. Your work is greatly appreciated. :)

**Comment by tsimonq2** [comment]
Thanks!
