### ISSUE TITLE
Build failures: ppa:saiarcot895/chromium-dev

### ISSUE THREAD

**Issue by kq01526** [saiarcot895/chromium-ubuntu-build#10]
@saiarcot895 :

The builds are failing [again](https://github.com/saiarcot895/chromium-ubuntu-build/issues/6):

https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+packages

**Comment by saiarcot895** [comment]
That's known. I was testing out a few changes that I'll be fixing/reverting by the next major version.

The last successful builds can still be downloaded.

**Comment by TwoLeaves** [comment]
I rely on these packages for hardware decoding on a Thinkpad T420s. Cheers. In particular I rely on the release for Ubuntu 14.04, as this is the only release the works on Debian 8. There is no pre-compiled chromium with hardware decoding indiscriminately enabled that I can find for Debian.

Unfortunately the most recent 14.04 amd64 build was on 2016-10-15. For reasons I do not understand, this build is old enough to no longer load half of the secure websites I visit. I am hoping for a new amd64 build to resolve this issue.

**Comment by saiarcot895** [comment]
@TwoLeaves It's looking like the two compilers on Trusty (GCC and Clang) are too old to compile Chromium. To continue supporting Trusty, I'll have to backport the compiler from 16.04.

**Comment by TwoLeaves** [comment]
Ah, that's a shame. Thanks for the info.
