### ISSUE TITLE
Chromium builds failing on Ubuntu 20.10

### ISSUE THREAD

**Issue by thetick1234567890** [saiarcot895/chromium-ubuntu-build#103]
Hi,

I upgraded my test machine to Ubuntu 20.10 and was looking for Chromium builds with vaapi.  I noticed the only 20.10 build failed with what looks like build configuration issue.  Could you please investigate so 20.10 packages and all Chromium 88 packages are built?

https://launchpadlibrarian.net/502537021/buildlog_ubuntu-groovy-amd64.chromium-browser_1%3A88.0.4292.2-0ubuntu1~ppa1~20.10.1_BUILDING.txt.gz

ERROR at //content/gpu/BUILD.gn:136:7: Undefined identifier
  if (is_desktop_linux && use_vaapi) {
      ^---------------

And thanks for all the builds as I'm happily running with functional video acceleration on Chromium 87 build with 20.04 Ubuntu on my laptop.

**Comment by lvicentesanchez** [comment]
I just installed Pop!_OS 20.10 and tried to use the ppa to install the beta version (87.0.4280.27) but the build also seems to be failing

**Comment by thetick1234567890** [comment]
Any updates for Groovy Gorilla as the builds have crashes the last couple builds with the following \:
[2656/38003] CC obj/third_party/brotli/enc/metablock.o
[2657/38003] AR obj/third_party/brotli/libenc.a
[2658/38003] LINK ./brotli
FAILED: brotli 
python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./brotli" -- /usr/bin/clang++ -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--threads -Wl,--thread-count=4 -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -nostdlib++ -pie -Wl,--disable-new-dtags -o "./brotli" -Wl,--start-group @"./brotli.rsp"  -Wl,--end-group  -ldl -lpthread -lrt
double free or corruption (!prev)
clang: error: unable to execute command: Aborted (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)

**Comment by saiarcot895** [comment]
Something odd is with Clang 11; I'm making changes to have it compile with Clang 10 instead. Beta will be the first to get that change, and if it builds there, I'll make the same change on Dev.

**Comment by tbergeron** [comment]
Stuck in the same situation, I cannot install chromium-browser since it installs that damn snap transition package instead. Is there any way of working around that? #104

**Comment by thetick1234567890** [comment]
I hate and boycott snaps also.  For chromium-browser you can just download the .dep files and install the .dep files on the command line with dpkg -i <name>.deb .  On my 20.04 machine the latest 87 version works great with vappi hardware acceleration.
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20152344/+files/chromium-browser_87.0.4280.20-0ubuntu1~ppa1~20.04.1_amd64.deb 
and 
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20152344/+files/chromium-codecs-ffmpeg-extra_87.0.4280.20-0ubuntu1~ppa1~20.04.1_amd64.deb

**Comment by tbergeron** [comment]
> I hate and boycott snaps also. For chromium-browser you can just download the .dep files and install the .deb files on the command line with dpkg -i .deb . On my 20.04 machine the latest 87 version works great with vappi hardware acceleration.
> https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20152344/+files/chromium-browser_87.0.4280.20-0ubuntu1~ppa1~20.04.1_amd64.deb
> and
> https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20152344/+files/chromium-codecs-ffmpeg-extra_87.0.4280.20-0ubuntu1~ppa1~20.04.1_amd64.deb

that's a great idea :D now I just need to figure out how to find the last working version of chromium beta for 20.10

it seems every build is failing, is this the page you used to find working builds? (https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta/+builds?build_state=all&build_text=&batch=75)

thanks a lot!

**Comment by thetick1234567890** [comment]
Yep the build is still failing but it did make progress and failed much later in the build process.

@saiarcot895 : Error looks like link or package issue with the clang++ compiler
/bin/sh: 1: /usr/bin/clang++: not found

**Comment by tbergeron** [comment]
Thanks for the help @thetick1234567890 I wish I could help more with this issue but my C++ is more than rusty 😆

**Comment by saiarcot895** [comment]
> @tbergeron Yep the build is still failing but it did make progress and failed much later in the build process. Hopefully we'll soon have a 2020.10 build of Chromium to test.
> 
> @saiarcot895 : Error looks like link or package issue with the clang++ compiler
> /bin/sh: 1: /usr/bin/clang++: not found

It's a typo I made in the build configuration that ended up affecting all versions of Ubuntu.

**Comment by thetick1234567890** [comment]
For 20.10 the 87 build failed with a seg fault while linking \:

[5157/44197] LINK ./flatc
FAILED: flatc 
python2 "../../build/toolchain/gcc_link_wrapper.py" --output="./flatc" -- /usr/bin/clang++-10 -Wl,--build-id -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed -fuse-ld=gold -Wl,--threads -Wl,--thread-count=4 -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -nostdlib++ -pie -Wl,--disable-new-dtags -o "./flatc" -Wl,--start-group @"./flatc.rsp"  -Wl,--end-group  -ldl -lpthread -lrt
/usr/bin/ld.gold: internal error in set_no_output_symtab_entry, at ../../gold/object.h:1814
clang: error: unable to execute command: Segmentation fault (core dumped)
clang: error: linker command failed due to signal (use -v to see invocation)

Anyway the 20.04 88 build was successful so I'll check that out tonight and see if hardware acceleration works.  Also I hope the zero copy using the DMA buffers is working but I don't think Chromium guys have resolved it yet.

**Comment by saiarcot895** [comment]
Yeah, something is very odd with Clang 10 and 11 on 20.10.

**Comment by thetick1234567890** [comment]
On 20.10 after installing 20.04 pipewire lib (https://packages.ubuntu.com/focal/libpipewire-0.2-1)  the 20.04 Chromium vaapi works fine with hardware acceleration on 20.10.

**Comment by tbergeron** [comment]
> On 20.10 after installing 20.04 pipewire lib (https://packages.ubuntu.com/focal/libpipewire-0.2-1) the 20.04 Chromium vaapi version 88 build works fine with hardware acceleration on 20.10. So I guess we all can live with this until the clang issue(s) with 2010 are resolved.

Ok so if I get it right, this means that on 20.10 I could 

Add the focal (20.04) PPA and install chromium for focal so:

```
sudo apt install chromium-browser/focal libpipewire-0.2-1
```

should do the trick? it gives me:

```
Package libpipewire-0.2-1 is not available, but is referred to by another package.
```

**Comment by thetick1234567890** [comment]
No don't use apt as it is impossible to get all the paths / holds correct and you might even break other applications depended on libpipewire. 

From a clean 2010 machine :

wget http://mirrors.kernel.org/ubuntu/pool/universe/p/pipewire/libpipewire-0.2-1_0.2.7-1_amd64.deb

wget https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20259544/+files/chromium-codecs-ffmpeg-extra_88.0.4315.5-0ubuntu1~ppa1~18.04.1_amd64.deb

wget https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+build/20259544/+files/chromium-browser_88.0.4315.5-0ubuntu1~ppa1~18.04.1_amd64.deb

sudo dpkg -i libpipewire-0.2-1_0.2.7-1_amd64.deb
sudo dpkg -i chromium-codecs-ffmpeg-extra_88.0.4315.5-0ubuntu1~ppa1~18.04.1_amd64.deb
sudo dpkg -i chromium-browser_88.0.4315.5-0ubuntu1~ppa1~18.04.1_amd64.deb

**Comment by tbergeron** [comment]
This actually works! This is amazing thanks so much 😀 

Only thing I wonder though is for updates? I guess once a newer version become available through the PPA apt will pick it up?

Thanks again! I've been scratching my head over this for a while.

**Comment by thetick1234567890** [comment]
Sure glad to help.  

For updates you can just pickup a new ffmpeg and a new browser debs from the focal directories and install them.  I not 100% sure but PPA will not be updated until the groovy directories actually have .deb to install :)

**Comment by saiarcot895** [comment]
There is now a deb for 20.04 available in the Dev PPA, but without Pipewire support (relevant for screen sharing on Wayland). The Beta PPA will be next (also without Pipewire support).

**Comment by thetick1234567890** [comment]
The chromium-browser - 1:88.0.4324.11-0ubuntu1~ppa2~20.10.1 build works fine on my decade old AMD/Intel laptops with hardware video decoding on 20.10.  Now if Chromium could just fix the issue with zero copy/ dma buffers (worked prior to ozone enabled on Linux) I would permanently switch to Chromium.  Right now Firefox zero copy video hardware acceleration works just as good but with out an extra memory copy so 30% less power consumed than Chromium!

**Comment by saiarcot895** [comment]
The beta PPA has a build for 20.10 amd64. Closing this bug.
