### ISSUE TITLE
Use Default Google API's?

### ISSUE THREAD

**Issue by dragonBall561** [saiarcot895/chromium-ubuntu-build#105]
Is there a way that the default Google API's for Chrome can be used? I know that in one Chromium Repository, [Chromium Win64](https://github.com/Hibbiki/chromium-win64), the file `sync.args`, line 15, it shows:

`use_official_google_api_keys = true`

Is there any way that it is possible to use this with this build?

Thanks!

**Comment by saiarcot895** [comment]
No, that argument in particular shouldn't be used here because this is not an official Google release.
