### ISSUE TITLE
Really Weird and Complicated Bug Downloading File

### ISSUE THREAD

**Issue by dragonBall561** [saiarcot895/chromium-ubuntu-build#106]
NOTE: I have 'Just Black: Midnight Monochrome'

What happens when I download a big file, and I try to close the window, but then Chromium stops me (as per norm) and I click continue downloading. It goes to downloads and when I open a new tab, it's all white!

Steps To Reproduce:
1. Install [Just Back: Midnight Monochrome, By The Chrome Team](https://chrome.google.com/webstore/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab)
1. Download a Big File, Big Enough that it takes at least 1-2 mins to download.
1. Try to exit Chromium
1. Click 'Keep Downloading'
1. It will open Downloads
1. Open a New Tab
1. It Is All White, Instead of Black

**Comment by saiarcot895** [comment]
Extensions aren't something I can help with here, unless it's something that doesn't happen on regular Chrome, but does in Chromium (and even then, I don't know how much I'll be able to help).
