### ISSUE TITLE
Why there is no patch for branch 4324 (version 88) present?

### ISSUE THREAD

**Issue by vasylenkoserhii** [saiarcot895/chromium-ubuntu-build#109]
Hi!
Is it possible that patch for branch 4324 will be added?
I see in comments that version 89 already mentioned in comments to 'master' and when I tried to apply patch from master to chromium 88/4324 I got:
```
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|Index: media/gpu/vaapi/vaapi_image_processor_backend.cc

```
seems like patch in master, despite comments about version 89, contains changes to files, which were removed prior version 88.

Thanks!

**Comment by saiarcot895** [comment]
I just pushed this. Sorry about the delays.
