### ISSUE TITLE
VAAPI-accelerated video: new flag required by Chromium 90/91, and please link in the PPA to Arch wiki

### ISSUE THREAD

**Issue by ronjouch** [saiarcot895/chromium-ubuntu-build#112]
Just a heads up that Chromium 91.0.4449.6 (maybe 90 too, I'm not sure) requires a new flag to enable VAAPI-accelerated video decoding: `--enable-features=VaapiVideoDecoder` .

---

Also, the [PPA's readme](https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev) currently reads:

```
== Hardware Video Decoding ==

To enable hardware video decoding, open chrome://flags, search for
"Hardware-accelerated video", enable the entry, and restart Chromium.
```

This isn't great advice, as 1. incomplete, and 2. changing all the time.

May I suggest the PPA readme to be blank, and simply link to the most up-to-date community-maintained doc on how to enable it, https://wiki.archlinux.org/index.php/Chromium#Hardware_video_acceleration ?

**Comment by saiarcot895** [comment]
PPA description has been updated to specify the current method of enabling VAAPI video decoding, as well as a link to the Arch wiki.
