### ISSUE TITLE
New version 92 builds ? New Hirsute Hippo builds ?

### ISSUE THREAD

**Issue by thetick1234567890** [saiarcot895/chromium-ubuntu-build#113]
Hi,

I just wanted to ask if a 92 build is coming soon ?  And also is there a  Hirsute Hippo build yet ?

**Comment by saiarcot895** [comment]
It is coming soon, I'm working on the beta PPA first.

**Comment by saiarcot895** [comment]
Closing this, since there is now a package for Hirsute for both Beta and Dev PPAs. However, there is an issue with those packages, which is being tracked in #114.
