### ISSUE TITLE
No flag for pipewire-capturer

### ISSUE THREAD

**Issue by MasinAD** [saiarcot895/chromium-ubuntu-build#127]
Version: chromium-browser 1:107.0.5304.62-0ubuntu1~ppa1~22.04.1 amd64
Repository: deb https://ppa.launchpadcontent.net/saiarcot895/chromium-beta/ubuntu/ jammy main

Under chrome://flags the flag #enable-webrtc-pipewire-capturer is missing. As I cannot share my screen on Wayland, I looked to enable it. Canonical's snap is missing it, too, but Google's Chrome has it.

**Comment by saiarcot895** [comment]
There was a build script issue. This should be fixed starting with `1:108.0.5359.40-0ubuntu1~ppa1` in the Beta PPA and `1:109.0.5410.0-0ubuntu1~ppa1` in the dev PPA.
