### ISSUE TITLE
chromium-browser 64 bits ?

### ISSUE THREAD

**Issue by mpalourdio** [saiarcot895/chromium-ubuntu-build#17]
Hello,

I'm actually using chromium 32 bits from the official ubuntu repositories. Is it possible to install through your PPA the 64 bits version ?

Could you please tell me how to force the 64 bits versions when installing via your PPA ?

Thanks.

**Comment by saiarcot895** [comment]
If you added the PPA through the normal way (using `add-apt-repository`), then you should already be using 64-bit Chromium.

How are you determining that you're using 32-bit Chromium?

**Comment by mpalourdio** [comment]
By looking at "about chromium". I suppose that if doesn't specify 64 bits, it's a 32 bits version. At least for chrome < v59.

BTW, the problem I encountered with chromium 58 is fixed with chromium 59. Thanks !
