### ISSUE TITLE
Upstream widevine support

### ISSUE THREAD

**Issue by pgera** [saiarcot895/chromium-ubuntu-build#18]
Is there something holding back widevine support in regular ubuntu packages ? Any way this can be upstreamed ? I find it strange that widevine doesn't work out of the box on Ubuntu (at least on trusty). I also see a debian contrib package (https://packages.debian.org/sid/chromium-widevine).

**Comment by saiarcot895** [comment]
This is up to the Ubuntu maintainer to decide whether or not to add this support.

**Comment by pgera** [comment]
Right, I mean is there any way you could submit a patch/pull request for this bug: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1652110 ? I'm guessing that they are interested in fixing it since it seems to be reported by the maintainer.

**Comment by oSoMoN** [comment]
Thanks for pointing that out, that issue had fallen off my radar.
[This change](http://bazaar.launchpad.net/~chromium-team/chromium-browser/artful-beta/revision/1400) should do the trick.

**Comment by pgera** [comment]
Thanks. This is fixed in chromium 63.
