### ISSUE TITLE
Hardware decode does not work on Ubuntu 18 LTS

### ISSUE THREAD

**Issue by montvid** [saiarcot895/chromium-ubuntu-build#29]
Hardware decode does not work on Ubuntu 18 LTS, no error messages on x11 just software decode - -ignore-gpu-blacklist does not work.

> vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Kaby Lake - 2.1.0

**Comment by saiarcot895** [comment]
Is this on the beta or dev version?

**Comment by montvid** [comment]
So any news on this? I tried enabling "--ignore-gpu-blacklist" but i still get "Disabled Features: video_decode"!!!

/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --ignore-gpu-blacklist --flag-switches-end

Accelerated video decode has been disabled, either via blacklist, about:flags or the command line.
Disabled Features: video_decode

**Comment by montvid** [comment]
I had to enable another switch in chrome://flags for hw decode to work "--enable-accelerated-video" I wonder why they are not enabled by default:

/usr/lib/chromium-browser/chromium-browser --enable-pinch --flag-switches-begin --enable-accelerated-video --ignore-gpu-blacklist --flag-switches-end

4k30fps does work but 4k60fps vp9 lags in youtube on my Intel hd620 kaby lake that supports this. :)

**Comment by saiarcot895** [comment]
Yeah, this code is from a patch that is trying to be merged in upstream, and the patch wants to add a flag to enable hardware acceleration.
