### ISSUE TITLE
Wrong color information on ryzen 

### ISSUE THREAD

**Issue by mathew0007** [saiarcot895/chromium-ubuntu-build#41]
Chromium-browser 72.0.3626.28-0ubuntu1~ppa1~18.04.1 (beta branch) on my new Ryzen 5 laptop (envy x360-13) has wrong color information with HW acceleration enabled (RGB buffer treated as YUV????). Payback seems fine (CPU load, sound and "fluidity") but colors are wrong (although shapes can be distinguished).
VLC plays everything fine (h264 1080p and hevc 4k->1080p with no CPU load).
I have 3 more Intel IGP systems that chromium plays fine.

vainfo:
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: mesa gallium vaapi
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
Ubuntu 18.04.1
Chromium-browser 72.0.3626.28-0ubuntu1~ppa1~18.04.1

![screenshot_2018-12-26_14-58-10](https://user-images.githubusercontent.com/46161611/50447210-5ae4e880-0922-11e9-91e8-3ed6fcfb0c3b.png)
![screenshot_2018-12-26_15-23-49](https://user-images.githubusercontent.com/46161611/50447211-5b7d7f00-0922-11e9-9996-e723dbfba33d.png)

**Comment by mathew0007** [comment]
I understand that. Unfortunately I have not compiled chromium yet, as my
previous experience with large SW projects were spending days trying to
figure what I need to install just to compile. I may eventually do this for
chromium, but in the mean time I'm open to testing new builds (as in a tar
archive) with maybe some extra logging for this topic.

**Comment by omen23** [comment]
sudo apt build-dep chromium-browser

**Comment by Lukypie** [comment]
This happens also on my AMD Radeon RX 580, and not on my intel laptop

**Comment by Lukypie** [comment]
On Manjaro Linux, using chromium-vaapi aur package, does not happen.

Not sure if that's a mesa regression/vaapi library or due to the different vaapi patch.

**Comment by vasylenkoserhii** [comment]
Seems like exactly this problem discussed here https://www.spinics.net/lists/dri-devel/msg198697.html and here https://bugs.freedesktop.org/show_bug.cgi?id=108937 and I checked solution proposed there (setting of allow_rgb10_configs=false environmental variable before starting chromium and it worked.

**Comment by Lukypie** [comment]
However I'm sure in Manjaro Linux is working fine using this AUR package
https://aur.archlinux.org/packages/chromium-vaapi/

Whether because of a workaround in mesa or in the package itself

**Comment by saiarcot895** [comment]
The AUR package appears to be doing the same thing that bug 108937 is recommending: to disable 10-bit color configs.

See [this](https://aur.archlinux.org/cgit/aur.git/tree/chromium-drirc-disable-10bpc-color-configs.conf?h=chromium-vaapi) config file getting applied.
