### ISSUE TITLE
Google Maps looks strange

### ISSUE THREAD

**Issue by Fail-Unsafe** [saiarcot895/chromium-ubuntu-build#45]
Google Maps looks sort of weird

![Google Maps screenshot](https://imgur.com/a2fyfMAl.png)

Chromium Version 73.0.3683.67 with Nvidia drivers 418.43. Ubuntu 18.10

**Comment by saiarcot895** [comment]
I see this issue as well, and I can't figure it out entirely. As a data point, running Chromium inside a VM with only software rendering support (no GPU passthrough or anything) doesn't show this issue.

**Comment by saiarcot895** [comment]
This has (likely) been fixed with the changes in e474186c46e9e5ac7e7a940f38f8a95f4c382160.
