### ISSUE TITLE
Video playback is jerky when using Mojo, while older GpuVideoDecoder is ok

### ISSUE THREAD

**Issue by donlucacorleone** [saiarcot895/chromium-ubuntu-build#54]
Hello all,
my configuration is:

Intel NUC 7CJYH with Celeron J4005 CPU @ 2.00GHz (which has the integrated Intel UHD Graphics 600 GPU).
Ubuntu 18.04.2 LTS.
Kernel 4.18.0-25-generic.

Chromium 72 got video hardware acceleration (I read "GpuVideoDecoder" in the media-internals page) and a 4K video played smoothly.

I just update Chromium to version 76 (and 77 too).
The same 4K video now is jerky/stuttering (I see GAM at 100% in the intel_gpu_top output), but the hw acceleration should be enabled because media-internals reports "MojoVideoDecoder".

VAINFO reports:
```
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Gemini Lake - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSlice
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

In version 72 flags are:
ignore-gpu-blacklist
enable-accelerated-video

In version 76 (and 77) flags are:
ignore-gpu-blacklist
_enable-accelerated-video_ is already enabled by default

Am I missing something?
Thanks

**Comment by JurgenWolf** [comment]
I switched back to the old custom 74 build from this post:
https://github.com/saiarcot895/chromium-ubuntu-build/issues/42#issuecomment-469730935
And now 1080p youtube works as expected using legacy GPU videodecoder... and no annoying errors for H264 profiles.

**Comment by JurgenWolf** [comment]
Just published by another victim:
https://github.com/saiarcot895/chromium-ubuntu-build/issues/54

So looks that this MojoVideoDecoder is 100% laggy and buggy.

**Comment by saiarcot895** [comment]
@donlucacorleone Is `ignore-gpu-blacklist` needed for your setup? Intel shouldn't have any issues.

**Comment by donlucacorleone** [comment]
> @donlucacorleone Is `ignore-gpu-blacklist` needed for your setup? Intel shouldn't have any issues.

Not needed, you're right. But still choppy :-(

**Comment by JurgenWolf** [comment]
Use 78 Beta - there MojoVideoDecoder works without issues... at least for me.

**Comment by donlucacorleone** [comment]
I come back after one year just to say that Chromium 84 beta is ok!
