### ISSUE TITLE
Unable to disable MojoVideoDecoder

### ISSUE THREAD

**Issue by MOZGIII** [saiarcot895/chromium-ubuntu-build#56]
Hello, `--disable-features=MojoVideoDecoder` does not seem to be doing anything. I still get `video_decoder | MojoVideoDecoder` at `chrome://media-internals/`

How can I force using old decoder?

**Comment by JurgenWolf** [comment]
Forget...
It is impossible to disable it since 76.
And it is very buggy in 76/77.
Use 78 Beta - there MojoVideoDecoder works without issues... at least for me.

**Comment by MOZGIII** [comment]
I came to the same conclusion regarding disabling it.

**Comment by saiarcot895** [comment]
Hardware acceleration usage has changed, and instead requires `--enable-features=VaapiVideoDecoder` to be passed in as a flag.

Closing this issue.
