### ISSUE TITLE
PPA beta builds get replaced by official builds

### ISSUE THREAD

**Issue by Cqoicebordel** [saiarcot895/chromium-ubuntu-build#61]
When you run `apt-cache policy chromium-browser` you can see that the official builds have a newer version number than the one from the PPA, which means it gets updated (and so, we lose HWA).
I worked around the issue by adding the -dev ppa (BTW, adding links to link the two PPAs would be helpful), but it's not an ideal solution. I'm not sure what the ideal solution would be though. Having a false version number, like 78.0.99999.3904.63 ?

```
$ apt-cache policy chromium-browser
chromium-browser:
  Installé : 79.0.3945.8-0ubuntu1~ppa1~19.04.1
  Candidat : 79.0.3945.8-0ubuntu1~ppa1~19.04.1
 Table de version :
 *** 79.0.3945.8-0ubuntu1~ppa1~19.04.1 500
        500 http://ppa.launchpad.net/saiarcot895/chromium-dev/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
     78.0.3904.70-0ubuntu0.19.04.4 500
        500 http://fr.archive.ubuntu.com/ubuntu disco-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu disco-security/universe amd64 Packages
     78.0.3904.63-0ubuntu1~ppa1~19.04.1 500
        500 http://ppa.launchpad.net/saiarcot895/chromium-beta/ubuntu disco/main amd64 Packages
     73.0.3683.103-0ubuntu1 500
        500 http://fr.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
```

**Comment by saiarcot895** [comment]
You can give a higher preference to the beta PPA, such that it won't upgrade to the version in the main repo even if it's higher than the latest beta version. The following in `/etc/apt/preferences.d/chromium` should do the trick:

```
Package: *
Pin: release o=LP-PPA-saiarcot895-chromium-beta
Pin-Priority: 700
```

**Comment by Cqoicebordel** [comment]
Thanks for the info !

If this is the way to go, adding a line about it in the PPAs would be welcome too, as I doubt I will be the only one with this kind of issue :)

**Comment by saiarcot895** [comment]
Done.
