### ISSUE TITLE
PPA: build also against current dev release

### ISSUE THREAD

**Issue by Esokrates** [saiarcot895/chromium-ubuntu-build#63]
@saiarcot895  Could you make the ppa build against current ubuntu dev release too (20.04)?

**Comment by pmartycz** [comment]
Hi, is there a chance we start building against 20.04 before its release? Suddenly this PPA is more relevant than ever due to problems with snap. Thank you.

**Comment by Esokrates** [comment]
@pmartycz He started building against 20.04 soon after I opened this bug report, so this not an issue anymore.

**Comment by pmartycz** [comment]
@Esokrates Have you tried actually using it? The [Packages](http://ppa.launchpad.net/saiarcot895/chromium-beta/ubuntu/dists/focal/main/binary-amd64/) file seem to be empty
 for `focal`

**Comment by saiarcot895** [comment]
That's because `focal` doesn't have Python 2, and Chromium needs (I think) Python 2 to build.

**Comment by Esokrates** [comment]
Ah ok, I've been using it on focal without problems but now that I checked I noticed that I didn't get the latest upgrade, I'm stuck at `Version 81.0.4021.2 (Developer Build) Ubuntu 20.04 (64-bit)`

**Comment by pmartycz** [comment]
> That's because `focal` doesn't have Python 2, and Chromium needs (I think) Python 2 to build.

You mean it's not installed by default? There's certainly `python2.7` package in the repo.

**Comment by saiarcot895** [comment]
The scripts still expect there to be a python symlink pointing to `/usr/bin/python2`. Supposedly, there'll be a package named `python-pointing-to-python2` provided in Focal, but I haven't seen this package yet.

**Comment by pmartycz** [comment]
Isn't the general approach to make such scripts depend on `/usr/bin/python2` explicitly from now? We can just patch shebangs to solve the problem or this is something less trivial?

**Comment by saiarcot895** [comment]
Builds are now available for Focal (20.04) amd64. I cannot build for i386 in the PPA due to the gradual deprecation of i386.
