### ISSUE TITLE
Patches (from master) not applying to ORIG_VERSION=80.0.3964.0 or later

### ISSUE THREAD

**Issue by timrichardson** [saiarcot895/chromium-ubuntu-build#67]
I've tried ORIG_VERSION=80.0.3964.0 and a later release under bionic

```
mv debian/patches/series.bionic debian/patches/series
quilt push -a

Applying patch suppress-newer-clang-warning-flags.patch
patching file build/config/compiler/BUILD.gn
Hunk #1 succeeded at 698 (offset 5 lines).
Hunk #2 FAILED at 1493.
1 out of 2 hunks FAILED -- rejects in file build/config/compiler/BUILD.gn
Patch suppress-newer-clang-warning-flags.patch does not apply (enforce with -f)
```

**Comment by akarshanbiswas** [comment]
suppress-newer-clang-warning-flags.patch ???

Why not add `-Wno-unknown-warning-option` compiler flag?

**Comment by timrichardson** [comment]
this fixes the patch in question:


Index: debian/patches/suppress-newer-clang-warning-flags.patch
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- debian/patches/suppress-newer-clang-warning-flags.patch	(revision 1bdb6fd68b7f6ef8bb24d4c869c914751048578a)
+++ debian/patches/suppress-newer-clang-warning-flags.patch	(revision 7cadd4bce083dba18d03cd4aecba97056f946248)
@@ -1,11 +1,11 @@
 Author: Olivier Tilloy <olivier.tilloy@canonical.com>
 Description: Do not use warning flags that require a newer Clang
 
-Index: dev/build/config/compiler/BUILD.gn
+Index: chromium-ubuntu-build/build/config/compiler/BUILD.gn
 ===================================================================
---- dev.orig/build/config/compiler/BUILD.gn
-+++ dev/build/config/compiler/BUILD.gn
-@@ -693,14 +693,6 @@ config("compiler") {
+--- chromium-ubuntu-build.orig/build/config/compiler/BUILD.gn	2019-12-22 19:55:19.875019232 +1100
++++ chromium-ubuntu-build/build/config/compiler/BUILD.gn	2019-12-22 20:00:39.705036702 +1100
+@@ -698,14 +698,6 @@
      ldflags += [ "-Wl,--no-rosegment" ]
    }
  
@@ -20,10 +20,13 @@
    # Pass the same C/C++ flags to the objective C/C++ compiler.
    cflags_objc += cflags_c
    cflags_objcc += cflags_cc
-@@ -1501,28 +1493,6 @@ config("default_warnings") {
-       if (current_toolchain == host_toolchain || !use_xcode_clang) {
-         # Flags NaCl (Clang 3.7) and Xcode 9.2 (Clang clang-900.0.39.2) do not
-         # recognize.
+@@ -1503,43 +1495,6 @@
+         cflags += [ "-Wno-nonportable-include-path" ]
+       }
+ 
+-      if (current_toolchain == host_toolchain || !use_xcode_clang) {
+-        # Flags NaCl (Clang 3.7) and Xcode 9.2 (Clang clang-900.0.39.2) do not
+-        # recognize.
 -        cflags += [
 -          # Ignore warnings about MSVC optimization pragmas.
 -          # TODO(thakis): Only for no_chromium_code? http://crbug.com/912662
@@ -34,18 +37,30 @@
 -
 -          # TODO(https://crbug.com/999871): Decide if we want to clean up the
 -          # codebase or just disable this.  Doesn't seem super useful, but
--          # also fires in only 4 files.
+-          # also fires in only 2 files.
 -          "-Wno-c99-designator",
 -
--          # This is a side effect of -Wc99-designator; easier to clean up.
--          "-Wno-reorder-init-list",
--
 -          # TODO(https://crbug.com/999886): Clean up, enable.
 -          "-Wno-final-dtor-non-final-class",
 -
 -          # TODO(https://crbug.com/1002945): Evaluate and possibly enable.
 -          "-Wno-sizeof-array-div",
 -        ]
- 
-         cflags_c += [
-           # TODO(https://crbug.com/995993): Clean up and enable.
+-
+-        cflags_c += [
+-          # TODO(https://crbug.com/995993): Clean up and enable.
+-          "-Wno-implicit-fallthrough",
+-        ]
+-        if (llvm_force_head_revision) {
+-          cflags += [
+-            # TODO(https://crbug.com/1016947) Clean up, enable.
+-            "-Wno-bitwise-conditional-parentheses",
+-
+-            # TODO(https://crbug.com/1016945) Clean up, enable.
+-            "-Wno-builtin-assume-aligned-alignment",
+-          ]
+-        }
+-      }
+     }
+   }
+ }

**Comment by timrichardson** [comment]
that is probably a stupid way to help ... patching a patch.

**Comment by timrichardson** [comment]
I'm just running into problem after problem, and now beyond my limited skills to fix. I would like a recent 80. release to build, but I can't get it to work (for 18.04), build errors which I think have been fixed but not yet pushed to github.

**Comment by saiarcot895** [comment]
I've updated the master branch yesterday, with the patches used to build 80.0.3964.0.

**Comment by timrichardson** [comment]
git hub still shows Nov 20 as most recent commit, it seems to me.

**Comment by saiarcot895** [comment]
See commits 488559cc49b996709a8aaa313c3d3a68215b07c1 and 70e3f33930194e288252707e413f86a0da7fc1ff. I made the actual commit a month ago, but didn't push it until yesterday.

**Comment by timrichardson** [comment]
Thanks, I'll try it later today (my day has just begun). The standard ubuntu builds of Chromium are newer than your ppa so my hardware decoding has disappeared, and building something more up to date is the most fun way to fix this.
