### ISSUE TITLE
Fix found for VAAPI/VDPAU errors on nVidia (Failed creating a GLX Pixmap for TFP)

### ISSUE THREAD

**Issue by dagraver** [saiarcot895/chromium-ubuntu-build#7]
DISCLAIMER: I'm in no way, shape or form a developer or expert of any kind, so, my apologies for not including patches and so on.

Up until now, if you used NVidia's proprietary driver, something like this showed up:

libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
[7976:7976:1222/103444.298949:ERROR:vaapi_tfp_picture.cc(56)] Failed creating a GLX Pixmap for TFP
[7976:7976:1222/103444.298958:ERROR:vaapi_video_decode_accelerator.cc(819)] Failed to allocate memory for a VaapiPicture
[7976:7976:1222/103444.298966:ERROR:vaapi_video_decode_accelerator.cc(288)] Notifying of error 4

By adding some additional diagnostic logging, I found that  gl_image_glx.cc(138)] glXChooseFBConfig failed.

Doing some research I found that the developers used to wrong value for GLX_BIND_TO_TEXTURE_TARGETS_EXT instead of GLX_TEXTURE_2D_BIT_EXT they used GLX_TEXTURE_2D_EXT. According to the specification[1](https://www.opengl.org/registry/specs/EXT/texture_from_pixmap.txt), this (GLX_TEXTURE_2D_EXT) is not a valid value for the glXChooseFBConfig() attributes. So the driver rightfully rejects this.

HOW TO FIX:
in ui/gl/gl_image_glx.cc (about line 128) change

GLX_BIND_TO_TEXTURE_TARGETS_EXT,      GLX_TEXTURE_2D_EXT,

to

GLX_BIND_TO_TEXTURE_TARGETS_EXT,      GLX_TEXTURE_2D_BIT_EXT,

recompile and all is well and video acceleration on NVidia should work as well.

**Comment by dagraver** [comment]
Now with added patch, I hope it's correct.

[fix_gl_image.txt](https://github.com/saiarcot895/chromium-ubuntu-build/files/671868/fix_gl_image.txt)

**Comment by saiarcot895** [comment]
@sjnewbury can you take a look at this?

**Comment by sjnewbury** [comment]
Makes sense.  I'll try it out and make sure it doesn't regress i965.

**Comment by dagraver** [comment]
Any progress on this? All I can say is that it works great for me, cpu usage is down to about 6% from 40-60% while decoding videos on YouTube and Twitch.TV (and probably others) on my GTX-770 with proprietary drivers.

**Comment by saiarcot895** [comment]
Ah, for some reason, I thought your patch was supposed to go into the `vdpau-va-driver` package (which has the `nvidia_drv_video.so`). I didn't realize this was for the main Chromium package.

In that case, I'll apply your patch to the next build I have.

**Comment by dagraver** [comment]
My apologies for that, in retrospect I wasn't really clear (I was just happy I got HW acceleration working) :)

But sjnewbury is correct in that it needs checking if it breaks anything for non-nVidia-users (it shouldn't, because the original call has invalid arguments and now it actually conforms to the spec).

Also, in my opinion this bug should also be reported upstream because of that reason. I don't think I'm the correct person for that, since I'm in no way an experienced developer and I only 'fixed' this problem by accident more or less.

Also, thank you and all others involved for getting this stuff done and keep maintaining it. Much appreciated!

**Comment by saiarcot895** [comment]
It appears that there are no regressions with this change on i965 (at least on my machine, so I'll be reporting this to upstream).

**Comment by sjnewbury** [comment]
On Fri, 2017-01-06 at 07:06 -0800, Saikrishna Arcot wrote:
> It appears that there are no regressions with this change on i965 (at
> least on my machine, so I'll be reporting this to upstream).
> —
> 
Concur, sorry for taking so long, been distracted.
