### ISSUE TITLE
Both beta and dev build failed on Xenial ?

### ISSUE THREAD

**Issue by abcfy2** [saiarcot895/chromium-ubuntu-build#76]
Hi, I find both beta and dev build failed on Xenial. Would you please fix the build ? Thanks.

https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev/+packages

https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta/+packages

**Comment by saiarcot895** [comment]
It's a work in progress.

**Comment by saiarcot895** [comment]
Dev is now available for Xenial amd64.

**Comment by saiarcot895** [comment]
Beta and Dev are now available for Xenial amd64.
