### ISSUE TITLE
Unable to install on pop os

### ISSUE THREAD

**Issue by purezen** [saiarcot895/chromium-ubuntu-build#78]
I am trying to install the chromium-dev package on pop os 19.10 installation. Expecting it to work since its based on Ubuntu 19.10. However I get the following error on running `sudo apt-get install chromium-dev`:

```
The following packages have unmet dependencies:
 chromium-browser : Depends: chromium (= 78.0.3904.97-1pop2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by saiarcot895** [comment]
Check to see if there's some file in `/etc/apt/preferences.d/` that gives a higher preference to PopOS's repos than any other repos. If so, you'll need to create a similar file for this PPA.

Also, the package in this PPA is named `chromium-browser`, not `chromium-dev`.

**Comment by Bearddyy** [comment]
For anyone looking here, I had this problem too and it was driving me nuts, 
I nearly switched to arch...
Solution was to edit the /etc/apt/preferences.d/ and add:

```
Package: *
Pin: release o=LP-PPA-saiarcot895-chromium-dev
Pin-Priority: 1002
```

System76 put their repos at priority 1001

I doubt there is any way to fix this from your side.  
Is this worth a note on the ppa description?

**Comment by Shogu** [comment]
Hi, thanks for your dev version and thanks for the tip, it works.

But now Pop!_OS want to update his own version of Chromium, cannot, and then keep asking me to install it each update. But it's not a big deal!

Greetings from France!

**Comment by saiarcot895** [comment]
@Bearddyy I generally don't want to add repo preferences that force taking packages from a certain repo, and instead want to leave that to the user.

**Comment by saiarcot895** [comment]
The PPA description has been updated, though (at least for the Chromium beta PPA).

**Comment by IvanBernatovic** [comment]
> Hi, thanks for your dev version and thanks for the tip, it works.
> 
> But now Pop!_OS want to update his own version of Chromium, cannot, and then keep asking me to install it each update. But it's not a big deal!
> 
> Greetings from France!

I found a way to get rid of Pop Shop chromium updates. First delete chromium-browser and chromium packages by running `sudo apt remove chromium-browser chromium && sudo apt autoremove`. Then, instead of pasting the snippet that @Bearddyy wrote to `/etc/apt/preferences.d/pop-default-settings`, paste it to `/etc/apt/preferences.d/chromium` (you'll have to create new file because it doesn't exist). Now run `sudo apt update && sudo apt install chromium-browser` and you'll have Chromium from this PPA and you won't have annoying update notifications for Chromium in Pop Shop.

**Comment by Shogu** [comment]
Hi Ivan and thanks a lot, it works like a charm!

With previous tip Pop Shop could'nt apply updates because of Chromium : i had to update with terminal instead of GUI way.

Now with your tip i can run PopShop as usual!

**Comment by IvanBernatovic** [comment]
@Shogu , no problem. The solution was actually already provided in description of chromium-beta PPA Launchpad page, as @saiarcot895 suggested. So credits to him!

**Comment by saiarcot895** [comment]
Added to Chromium Dev PPA description.
