### ISSUE TITLE
Chromium uses only FFmpegVideoDecoder

### ISSUE THREAD

**Issue by Oober** [saiarcot895/chromium-ubuntu-build#89]
I have successfully used Chromium for viewing hardware-accelerated videos for a long time. However, something weird have been happened.

From media-internals:

___
00:00:05.064 | kVideoDecoderName | "MojoVideoDecoder"
00:00:05.064 | kIsPlatformVideoDecoder | true
00:00:05.065 | info | "Selected MojoVideoDecoder for video decoding, config: codec: h264, profile: h264 main, level: not available, alpha_mode: is_opaque, coded size: [320,240], visible rect: [0,0,320,240], natural size: [320,240], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
00:00:05.065 | pipeline_state | "kPlaying"
00:00:05.066 | audio_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
00:00:05.076 | warning | "video fallback to new decoder after initial decode error."
00:00:05.076 | info | "Failed to initialize VpxVideoDecoder"
00:00:05.076 | info | "Failed to initialize Dav1dVideoDecoder"
00:00:05.077 | kIsVideoDecryptingDemuxerStream | false
00:00:05.077 | kVideoDecoderName | "FFmpegVideoDecoder"
00:00:05.077 | kIsPlatformVideoDecoder | false
00:00:05.077 | info | "Selected FFmpegVideoDecoder for video decoding, config: codec: h264, profile: h264 main, level: not available, alpha_mode: is_opaque, coded size: [320,240], visible rect: [0,0,320,240], natural size: [320,240], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
___

So, it tries to use MojoVideoDecoder but fallbacks into FFmpegVideoDecoder, I am using Nvidia Proprietary Driver and vdpau-va-driver is installed. What happened? Any workarounds?

**Comment by Oober** [comment]
Switched to chromium-beta, which works out-of-the-box.

**Comment by saiarcot895** [comment]
If you start Chromium from the command line, what do you see?

**Comment by saiarcot895** [comment]
Also, what version of Chromium is this? What version of Ubuntu are you on?

**Comment by Oober** [comment]
This was prior to recent version from chromium-dev ppa. Not tested with the recent version. Mint 19.3.

**Comment by Oober** [comment]
This behavior occurs again in recent build from beta ppa (Version 87.0.4280.20 (Developer Build) Built on Ubuntu 20.04, running on LinuxMint 20 (64-bit)

Nvidia proprietary drivers, vdpau-va-driver installed.

It says there is a "VDA error 4" seen from media-internals. Same behavior; after trying to initialize MojoVideoDecoder, it failbacks into FFMpegDecoder.

**Comment by Oober** [comment]
See https://github.com/saiarcot895/chromium-ubuntu-build/issues/91#issuecomment-711087397

Might be a duplicate.
