### ISSUE TITLE
iHD driver doesn't work with the latest build

### ISSUE THREAD

**Issue by Sraw** [saiarcot895/chromium-ubuntu-build#90]
As now `iHD` is the default driver for intel GPU, the chromium's hardware acceleration seems to be broken. When I change to the older `i965` driver, it works again.

Will the new driver be supported in the future?

**Comment by saiarcot895** [comment]
Just to check, is this on 20.04?

**Comment by Sraw** [comment]
Yes, it is on 20.04.

**Comment by saiarcot895** [comment]
Can you post the error message that you're seeing when you run `chromium-browser` from the command line? If there's no error message there, can you post the output of `chromium-browser --enable-logging=stderr --log-level=0 --vmodule=vaapi_wrapper=4,vaapi_video_decode_accelerator=4`?

**Comment by saiarcot895** [comment]
Never mind, tracking this in #83.
