### ISSUE TITLE
Ubuntu20.04, NVIDIA, vaapi 

### ISSUE THREAD

**Issue by shenlijun** [saiarcot895/chromium-ubuntu-build#95]
Sorry for my poor english……

I have tested chromium 83 which supported hardware acceleration perfectly

But newer chromium won`t do that.

I tested mpv with  --hwdec=vaapi, no hardware acceleration.

But mpv with --hwdec=vaapi-copy, hardware acceleration perfectly.

Maybe chromium has the same problem?

**Comment by shenlijun** [comment]
vaapi-copy using intel driver, not NVIDIA

**Comment by saiarcot895** [comment]
Do you know what the difference is between `vaapi` and `vaapi-copy`?

**Comment by shenlijun** [comment]
> Do you know what the difference is between `vaapi` and `vaapi-copy`?

copies video back into system RAM，

performance loss but decoding with GPU

This maybe a problem with the graphics card driver

Is it possible to fallback to vaapi-copy when vaapi is not available？

**Comment by shenlijun** [comment]
> Do you know what the difference is between `vaapi` and `vaapi-copy`?

hardware acceleration comes back with recent update ……

**Comment by saiarcot895** [comment]
Closing as hardware acceleration was reported to be working.
