### ISSUE TITLE
Stop using custom user agent

### ISSUE THREAD

**Issue by Recydywa** [saiarcot895/chromium-ubuntu-build#96]
The current dev build from your PPA has a custom user agent which makes Netflix and probably other streaming services angry. You cannot stream anything until you change the user agent to a generic one.

This was also a problem with snap until they changed it to generic user agent.

https://forum.snapcraft.io/t/chromium-stop-using-custom-user-agent-work-towards-generic-one/17225

You should remove Ubuntu Chromium/86.0.4221.3 and only leave the Chrome part.

**Comment by saiarcot895** [comment]
Fixed in caa44aef2aca19455b6a0def075578c676683421.
