### ISSUE TITLE
WideVine not Working

### ISSUE THREAD

**Issue by dragonBall561** [saiarcot895/chromium-ubuntu-build#99]
To install Widevine, I use these steps:

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
mkdir chrome
dpkg -x ./*.deb ./chrome  # My only Deb file in that dir.
cd chrome
cd opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/
cp libwidevinecdm.so ~/.config/chromium
```
Exit Chromium
Open Chromium
Netflix doesn't work
Log Out
Log In
Open Chromium
Netflix Doesn't Work
Restart
Log In
Open Chromium
Netflix Doesn't Work

How to make Netflix Work?

Chromium: 85.0.4183.59 (Developer Build) Built on Ubuntu 20.04, running on LinuxMint 20 (64-bit)
Using Linux Mint 20.
I installed Ubuntu Gnome.
I am using Ubuntu Gnome.

**Comment by toguro-gh** [comment]
@dragonBall561 

Please copy the libwidevinecdm.so file to the /usr/lib/chromium-browser/WidevineCdm/_platform_specific/linux_x64/
directory and test again. (You can test here too: https://bitmovin.com/demos/drm )

So the steps are changed to something like this:

```
mkdir chrome
cd chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -x *.deb ./
cd opt/google/chrome/WidevineCdm/_platform_specific/linux_x64/
sudo mkdir -p /usr/lib/chromium-browser/WidevineCdm/_platform_specific/linux_x64/
sudo cp libwidevinecdm.so /usr/lib/chromium-browser/WidevineCdm/_platform_specific/linux_x64/
 ```

**Comment by dragonBall561** [comment]
Okay I will try

**Comment by dragonBall561** [comment]
Netflix doesn't work still

**Comment by dragonBall561** [comment]
But bitmovin does...
Is there something wrong with netflix?

**Comment by dragonBall561** [comment]
![sc](https://user-images.githubusercontent.com/61358474/95357980-88e8b200-0896-11eb-97fd-71ae0bfe2bca.png)

**Comment by dragonBall561** [comment]
This is from Netflix
![sc1](https://user-images.githubusercontent.com/61358474/95358149-ba617d80-0896-11eb-9a43-4bbb2088364f.png)

**Comment by dragonBall561** [comment]
Clearing Site data didn't help.

**Comment by toguro-gh** [comment]
I don't have Netflix access, but for HBO GO I have to change the user agent to get it working.

```
chromium-browser --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
```

**Comment by dragonBall561** [comment]
Yes Yes Thank You So Much!!!!!!
:)

**Comment by dragonBall561** [comment]
I had to do the Google Chrome User-Agent.
Just change the executing of the desktop files in /usr/share/applications.
